// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7vGFDBSX1YMOa5MqqzAdM14UeF7YxHo4',
    appId: '1:949885876375:web:f6b3e4b769b2bcf4cbd1d2',
    messagingSenderId: '949885876375',
    projectId: 'aljoodlaw-201e8',
    authDomain: 'aljoodlaw-201e8.firebaseapp.com',
    storageBucket: 'aljoodlaw-201e8.appspot.com',
    measurementId: 'G-5CGK9TY9R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxuzYM-qV3vbSCGeHn4VhKuseiI7qQXM',
    appId: '1:949885876375:android:0307bc20459d29a0cbd1d2',
    messagingSenderId: '949885876375',
    projectId: 'aljoodlaw-201e8',
    storageBucket: 'aljoodlaw-201e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnsNjEwFEaOvQxU_pyHU-cM7aKzwzHso',
    appId: '1:949885876375:ios:445cb43631553f93cbd1d2',
    messagingSenderId: '949885876375',
    projectId: 'aljoodlaw-201e8',
    storageBucket: 'aljoodlaw-201e8.appspot.com',
    iosBundleId: 'com.flyweb.application.OneSignalNotificationServiceExtension',
  );
}
